---
title: "Clustering"
author: "Rohan Patel"
date: "2023-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("cluster", quietly = TRUE)) {
  install.packages("cluster")
}
library(cluster)

if (!requireNamespace("factoextra", quietly = TRUE)) {
  install.packages("factoextra")
}
library(factoextra)

if (!requireNamespace("dbscan", quietly = TRUE)) {
  install.packages("dbscan")
}
library(dbscan)
```


```{r}
setwd("..")
data <- read_csv('Data/cleaned_data.csv')

diagnosis_column_index <- which(colnames(data) == "Diagnosis")
x_data = data[, -diagnosis_column_index]
y_data = data[, diagnosis_column_index]
# Scaling
x_data_scaled <- scale(x_data)
#PCA
pca_result <- prcomp(x_data_scaled)
variance_explained <- round((pca_result$sdev^2) / sum(pca_result$sdev^2) * 100, 2)
```
```{r, echo = False}
## Splitting the data randomly in the ratio 0.8
#set.seed(123)
#sample <- sample(c(TRUE, FALSE), nrow(data), replace=TRUE, prob=c(0.8,0.2))
#train_data <- data[sample, ]
#test_data <- data[!sample, ]

## Create x_train, y_train, x_test, y_test
#diagnosis_column_index <- which(colnames(train_data) == "Diagnosis")
#x_train <- train_data[, -diagnosis_column_index]
#y_train <- train_data[, diagnosis_column_index]
#x_test <- test_data[, -diagnosis_column_index]
#y_test <- test_data[, diagnosis_column_index]
```


## K Means
```{r}
k <- 4  # number of clusters
kmeans.fit <- kmeans(x_data_scaled, centers = k, nstart = 20)

fviz_cluster(kmeans.fit, data = x_data_scaled,
             palette = c("#2E9FDF", "#00AFBB", "#E7B800", "#792536"), 
             geom = "point",
             ellipse.type = "convex", 
             ggtheme = theme_bw()
             )
```

```{r}
# Plotting vs actual labels
pca_result <- prcomp(x_data_scaled)
plot(pca_result$x[, 1], pca_result$x[, 2], col = kmeans.fit$cluster, pch = (1:4), main = "K-Means Clustering with Actual labels", xlab=paste('Dim1 [',variance_explained[1],'%]',sep = ''), ylab=paste('Dim2 [',variance_explained[2],'%]',sep = ''), xlim=c(-3,4), ylim=c(-3, 3))
points(pca_result$x[, 1], pca_result$x[, 2], col = y_data[[1]]+10, pch = (15:18))
legend("topleft", legend = c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4", "Asthama", "COPD", "HC", "Infected"), col = c(1, 1), pch = c(1,2,3,4, 15,16,17,18), title = "Groups")

```


## Hirarchaial 
```{r}
# Perform hierarchical clustering
hclust_result <- hclust(dist(x_data_scaled))

# Plot the dendrogram
plot(hclust_result, main = "Hierarchical Clustering Dendrogram", xlab = "Observations", sub = NULL)

# Cut the tree to create clusters
num_clusters <- 4
clusters <- cutree(hclust_result, num_clusters)
rect.hclust(hclust_result, k = num_clusters, border = 2:num_clusters)
```

## DBSCAN
```{r}
# Set the parameters for DBSCAN
eps <- 0.5  # epsilon, the radius of the neighborhood
minPts <- 5  # minimum number of points to form a dense region (including the point itself)
dbscan_result <- dbscan(x_data_scaled, eps = eps, MinPts = minPts)

# Visualize the clusters
plot(x_data_scaled, col = dbscan_result$cluster + 1, pch = 20, main = "DBSCAN Clustering", xlab = "X-axis", ylab = "Y-axis")
legend("topright", legend = unique(dbscan_result$cluster), col = unique(dbscan_result$cluster) + 1, pch = 20, title = "Clusters")
```


