```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Install and load necessary libraries
if (!requireNamespace("readr", quietly = TRUE)) {
  install.packages("readr")
}
library(readr)

if (!requireNamespace("ROSE", quietly = TRUE)) {
  install.packages("ROSE")
}
library(ROSE)

if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
library(dplyr)

if (!requireNamespace("tidyr", quietly = TRUE)) {
  install.packages("tidyr")
}
library(tidyr)

if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
library(ggplot2)

if (!requireNamespace("pheatmap", quietly = TRUE)) {
  install.packages("pheatmap")
}
library(pheatmap)
```

# Load necessary libraries
```{r}
library(readr)
library(ROSE)
library(dplyr)
library(tidyr)
library(ggplot2)
```


# Importing the data
```{r}
setwd("..")
data <- read_csv('Data/Exasens.csv')
head(data)
data <- data[-c(1, 2), ]
data <- data[, -c(9:12)]
data <- data %>% setNames(c('ID', 'Time', 'Imaginary Part: Min', 'Imaginary Part: Avg', 'Real Part: Min', 'Real Part: Avg', 'Diagnosis'))
head(data)
```

# Data Cleaning and Balancing
```{r}
str(data)
data[c('Imaginary Part: Min', 'Imaginary Part: Avg', 'Real Part: Min', 'Real Part: Avg')] <- lapply(data[c('Imaginary Part: Min', 'Imaginary Part: Avg', 'Real Part: Min', 'Real Part: Avg')], as.numeric)
str(data)
summary(data)
```
# What is this Imaginary Part/Real Part?
```{r}
data <- na.omit(data)
```

# Checking for class imbalance
```{r}
table(data$Diagnosis)
```

# Balancing the classes using ROSE
```{r}
data_balanced <- ovun.sample(Diagnosis ~ ., data = data, method = "over", N = length(data$Diagnosis[data$Diagnosis == "Negative"]), seed = 123)
```

# Display the resampled DataFrame
```{r}
data_balanced_df <- data.frame(data_balanced$X)
names(data_balanced_df) <- names(data)
head(data_balanced_df)
str(data_balanced_df)
setwd("..")
write.csv(data_balanced_df, 'Data/cleaned_data.csv', row.names = FALSE)
```
